### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by makuto11** [vaeinoe/moraydular#2]
Hey, Would be possible to get the schematic?
Thanks in advance

**Comment by vaeinoe** [comment]
Hi! There aren't any separate schematics for the power distribution boards because they're so simple - I just drew them in the PCB layout view directly I think. But you can get the free Diptrace app and open the board files with it, and figure out the schematic from the traces very easily.

The prototype power supply design (Virta) does have schematic file included, because it's somewhat more complex a board. You can also open that in Diptrace.

Hope this helps!
